version: '3'
services: 
  db:
    image: 'postgres:latest'
    environment: 
      POSTGRES_PASSWORD: 12345678+
      POSTGRES_USER: postgres
      POSTGRES_DB: trabalho
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

